# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go information
      run: |
          go version
          go env
          
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v main.go

    - name: Test
      run: | 
          go test -v glob/compiler/match
          go test -v glob/compiler
          go test -v glob/syntax/ast
          go test -v glob/syntax/lexer
          go test -v glob/util/runes
          go test -v glob/utils/strings
          go test -v glob/
          go test -v qrterminal/qrcode/coding
          go test -v qrterminal/qrcode/gf256
          go test -v password/
          go test -v main.go

  build-test-windows:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go information
      run: |
          go version
          go env
          
    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v main.go

    - name: Test
      run: go test -v main.go
