# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: off    
    steps:
    - uses: actions/checkout@v3
      with:
          path: ./src/github.com/${{ github.repository }}
          fetch-depth: 5

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go information
      run: |
          go version
          go env
          echo ${GOROOT}
          echo ${GOPATH}
          
    - name: Install dependencies
      env: 
           GOPATH: ${{ runner.workspace }}
      run: |
          echo ${GOPATH}
          pwd
          go get .

    - name: Build
      env: 
           GOPATH: ${{ runner.workspace }}
      run: |
          echo ${GOPATH}
          pwd
          go build -v main.go

    - name: Test
      env: 
           GOPATH: ${{ runner.workspace }}
      run: |
          echo ${GOPATH}
          pwd
          go test -v main.go
